spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.106.128:3306/sell?characterEncoding=utf-8&useUnicode=true&useSSL=false
  rabbitmq:
    host: 192.168.99.100
    port: 32770
    username: guest
    password: guest
  jpa:
    show-sql: true
